import { CARD_FACES } from "@arcana/core"

/** Inline the generated SVG so it inherits the theme's CSS custom properties.
 *
 * An <img> would not: the face uses var(--card-line) and friends, and those
 * do not cross an image boundary. The markup is generated by our own build,
 * never user input, which is what makes the inline safe.
 */
export function CardFace({
  slug,
  reversed = false,
  className = "",
}: {
  slug: string
  reversed?: boolean
  className?: string
}) {
  const svg = CARD_FACES[slug]
  if (!svg) return null
  return (
    <div
      className={`art${reversed ? " reversed" : ""}${className ? ` ${className}` : ""}`}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}
